# Anaconda
- 종합 선물 세트 : python + 모듈 + Jupyter Notebook

# Jupyter Notebook
# Cell

# Command mode
- 셀 자체에 명령을 내림, 셀을 추가, 복사, 이동, 삭제, ...
- a(bove) : 현재 셀 위에 셀 추가
- b(elow) : 현재 셀 아래에 셀 추가
- x       : 현재 셀 자르기, 삭제 대용으로 사용

# Edit mode
- 셀 안에다가 무언가 입력
- 셀 단위로 실행 : shift + enter
- 셀의 맨 마지막 코드를 자동으로 출력
- markdown 사용가능 => 목차

In [6]:
3 + 4
3 - 4
3 * 4
3 / 4

0.75

# 제목
## 소제목
## 소제목2

# 데이터 분석
- 데이터 : 행과 열이 있는 2차원 테이블
- 행 : 구체적인 개별 데이터
- 열 : 데이터의 속성, 하나의 데이터 타입으로 통일이 되어야 함
- 리스트, 딕셔너리만 가지고 데이터 다루기가 힘듦 => 새로운 자료구조 도입! Pandas

In [ ]:
# json 형식
[{'이름' : ' 동그라미', '직급' : '부장', '나이' : 40, '성별' : '여자'},
{'이름' : ' 세모', '직급' : '과장', '나이' : 35, '성별' : '남자'}]

# json vs xml

In [ ]:
[].
{}.

In [ ]:
## Pandas
- 데이터 분석에 적합한 새로운 자료구조 2개를 제공
- Series, DataFrame

In [10]:
import pandas as pd

In [ ]:
### Series
- 1차원 자료구조
- 구성요소 2개 : index, values
- 순서있음 => 슬라이싱, ...

In [25]:
# A, B, C, D, E
math = [90,89,91,92,90]

math_sr = pd.Series(math, index=['A','B','C','D','E'])

In [33]:
# 데이터 접근 => 인덱스
math_sr['A']

np.int64(90)

In [34]:
# 순서로도 접근가능
math_sr.iloc[0]

np.int64(90)

In [30]:
# 슬라이싱 => 범위로 가져오기
math_sr[:2]

A    90
B    89
dtype: int64

In [32]:
math_sr[-2:]

D    92
E    90
dtype: int64

In [35]:
math_sr.sort_values()

B    89
A    90
E    90
C    91
D    92
dtype: int64

In [39]:
math_sr.sort_values(ascending=False)

D    92
C    91
A    90
E    90
B    89
dtype: int64

In [40]:
# 필터링
# 조건에 맞는 데이터만 가져오기
math_sr[ math_sr > 90 ]

C    91
D    92
dtype: int64

In [41]:
eng = [91,92,90,91,89]

eng_sr = pd.Series(eng, index=['A','B','C','D','E'])

In [47]:
math_sr + eng_sr
math_sr - eng_sr
math_sr * eng_sr
math_sr / eng_sr
math_sr // eng_sr
math_sr % eng_sr

A    90
B    89
C     1
D     1
E     1
dtype: int64

In [49]:
# 시리즈와 값 하나 연산
# 데이터 타입에 맞춰서 (인덱스의) 값 하나를 다 연산시켜 줌
math_sr + 100

A    190
B    189
C    191
D    192
E    190
dtype: int64

In [48]:
(math_sr + eng_sr ) / 2

A    90.5
B    90.5
C    90.5
D    91.5
E    89.5
dtype: float64

In [ ]:
### DataFrame
- 2차원 자료구조
- 구성요소 3개 : column, index, values
- 순서는 기본적으로 행방향

In [58]:
# A, B, C, D, E
math = [90,89,91,92,90]
eng = [91,92,90,91,89]
kor = [90,91,92,90,89]

grade_df = pd.DataFrame({'math':math, 'kor':kor, 'eng':eng}, index=['A','B','C','D','E'])

In [61]:
# 데이터 접근하기
# 기본적으로 컬럼
grade_df['math']

# 결과를 보면 series형태로 나옴

A    90
B    89
C    91
D    92
E    90
Name: math, dtype: int64

In [64]:
# 한번에 컬럼을 여러개를 선택하려면 => 리스트로 묶어서 하나로 입력 ★

grade_df[['math', 'eng']]

   math  eng
A    90   91
B    89   92
C    91   90
D    92   91
E    90   89

In [65]:
# []
1. 리스트 생성
2. 자료구조에서 데이터 꺼낼 때 ★★ => 인덱싱

딕셔너리[키]
리스트[순서]

SyntaxError: invalid character '★' (U+2605) (2766084400.py, line 3)

In [67]:
# 인덱스를 기준으로 선택
# .loc[인덱스]

grade_df.loc['A']

math    90
kor     90
eng     91
Name: A, dtype: int64

In [69]:
# df에서 바로 한 값에 접근하기
# .loc[인덱스, 컬럼]

grade_df.loc[ 'A', 'math']

np.int64(90)

In [71]:
grade_df['math']['A'] 
# grade_df['math']['A'] = 100

np.int64(90)

In [78]:
grade_df.loc['A', 'math'] = 92

In [74]:
# grade_df['math']['A'] 
grade_df.loc['A', 'math']

np.int64(100)

In [75]:
# 행과 열 순서
# .iloc[행 순서, 열 순서]

grade_df.iloc[1,0]

np.int64(89)

In [79]:
grade_df[:2]

   math  kor  eng
A    92   90   91
B    89   91   92

In [81]:
# 행과 열 양방향 슬라이싱

grade_df.iloc[:3,:2]

   math  kor
A    92   90
B    89   91
C    91   92

In [ ]:
맨 마지막 열 빼고 다 가져오기

In [83]:
grade_df.iloc[:,:-1]

   math  kor
A    92   90
B    89   91
C    91   92
D    92   90
E    90   89

In [87]:
# df의 기능들
grade_df.sort_values('math', ascending = False)

# 기본은 오름차순(True), 정렬

   math  kor  eng
A    92   90   91
D    92   90   91
C    91   92   90
E    90   89   89
B    89   91   92

In [88]:
# 기준을 여러개로
grade_df.sort_values(['kor','math'], ascending = False)

   math  kor  eng
C    91   92   90
B    89   91   92
A    92   90   91
D    92   90   91
E    90   89   89

In [90]:
# 필터링
# 1. 조건을 줄 때는 어떤 컬럼을 기준으로 조건을 주는지 명확히!

# grade_df[ grade_df > 90 ] !error! 
grade_df[ grade_df['math'] > 90 ]

   math  kor  eng
A    92   90   91
C    91   92   90
D    92   90   91

In [95]:
# 2. 조건 2개일 때~
# 논리연산 : and(&), or(|), not(~)

grade_df[ (grade_df['math'] >= 90) & grade_df['eng'] >= 90]

Empty DataFrame
Columns: [math, kor, eng]
Index: []

In [96]:
# 3. 조건이 3개 이상일 때
# 비교연산을 먼저 하고 변수에 할당시켜서 사용

grade_df[ (grade_df['math']>=90) &  (grade_df['eng']>=90) &  (grade_df['kor']>=90) ] # 좋지 않음

   math  kor  eng
A    92   90   91
C    91   92   90
D    92   90   91

In [99]:
# 더 나은 방식
cond1 = grade_df['math'] >= 90
cond2 = grade_df['eng'] >= 90
cond3 = grade_df['kor'] >= 90
grade_df[ cond1 & cond2 & cond3 ]

   math  kor  eng
A    92   90   91
C    91   92   90
D    92   90   91

In [104]:
# 시리즈의 연산
# df에서 어떤 속성을 선택해서 연산을 시키고 새로운 속성을 계산함
# => 기존의 df에 붙여서 같이 분석해 줌

grade_df['total'] = grade_df['math'] + grade_df['eng'] + grade_df['kor']

In [106]:
grade_df['avg'] = grade_df['total'] / 3

grade_df

In [107]:
grade_df

   math  kor  eng  total        avg
A    92   90   91    273  91.000000
B    89   91   92    272  90.666667
C    91   92   90    273  91.000000
D    92   90   91    273  91.000000
E    90   89   89    268  89.333333

In [ ]:
# jupyter notebook location
# c=> user => computer name

In [ ]:
# 엑셀 파일을 읽어와서 DF로 만드는 연습
- 컬럼
    - 사용할 컬럼 선택
    - 컬럼명을사용하기 좋게 바꾸기

- 인덱스
    - 보통의 경우 0, 1, 2, 3, 4, ...
    - 시계열 데이터의 경우 인덱스를 datetime과 같은 시간형식으로 세팅을 하기도
- 데이터값
    - 결측(빠진) 데이터 처리 for example => null
    - 데이터 타입 체크

In [ ]:
## 1. 엑셀 데이터 읽어 오기
- read_excel
- 첫번째 행을 컬럼으로 세팅하고 두번째 행부터는 데이터 값으로 입력
- 인덱스는 0, 1, 2, 3, ...으로 세팅

In [112]:
# 메타문자
# \ + 약속된 문자 => 특수한 효과
# r => raw

print(r'python\tpython')

python\tpython

In [116]:
path = r"C:\Users\KDA\Downloads\졸업생의 진로 현황(전체).xlsx"
# pd.read_excel(path, sheet_name= '졸업생의 진로 현황(중)')

raw_df = pd.read_excel(path)

## 2. 컬럼 정리
- 사용할 컬럼 선택
- 컬럼명을 사용하기 좋게 바꾸기

In [117]:
raw_df.columns

'지역', '정보공시 \n 학교코드', '학교명', '졸업자.2', '(특수목적고)과학고 진학자.2', '(특수목적고)외고ㆍ국제고 진학자.2'
# 학교명 << unique하진 않음

Index(['시도교육청', '지역교육청', '지역', '정보공시 \n 학교코드', '학교명', '학교급코드', '설립구분', '주야간',
       '제외여부', '제외사유', '졸업자', '졸업자.1', '졸업자.2', '일반고 진학자', '일반고 진학자.1',
       '일반고 진학자.2', '일반고 진학자.3', '특성화고 진학자', '특성화고 진학자.1', '특성화고 진학자.2',
       '특성화고 진학자.3', '(특수목적고)과학고 진학자', '(특수목적고)과학고 진학자.1', '(특수목적고)과학고 진학자.2',
       '(특수목적고)과학고 진학자.3', '(특수목적고)외고ㆍ국제고 진학자', '(특수목적고)외고ㆍ국제고 진학자.1',
       '(특수목적고)외고ㆍ국제고 진학자.2', '(특수목적고)외고ㆍ국제고 진학자.3', '(특수목적고)예고ㆍ체고 진학자',
       '(특수목적고)예고ㆍ체고 진학자.1', '(특수목적고)예고ㆍ체고 진학자.2', '(특수목적고)예고ㆍ체고 진학자.3',
       '(특수목적고)마이스터고 진학자', '(특수목적고)마이스터고 진학자.1', '(특수목적고)마이스터고 진학자.2',
       '(특수목적고)마이스터고 진학자.3', '(자율고)자율형사립고 진학자', '(자율고)자율형사립고 진학자.1',
       '(자율고)자율형사립고 진학자.2', '(자율고)자율형사립고 진학자.3', '(자율고)자율형공립고 진학자',
       '(자율고)자율형공립고 진학자.1', '(자율고)자율형공립고 진학자.2', '(자율고)자율형공립고 진학자.3', '기타 진학자',
       '기타 진학자.1', '기타 진학자.2', '기타 진학자.3', '진학자 계', '진학자 계.1', '진학자 계.2',
       '진학자 계.3', '취업자', '취업자.1', '취업자.2', '취업자.3', '(미진학자)무직자 및 미상',
       '(미진학자)무직자 및 미상.1', '(미진학자)무직자 및 미상.2', '(미진학자)무직자 및 미상.3'],
      dtype='str')

In [118]:
use_cols = ['지역', '정보공시 \n 학교코드', '학교명', '졸업자.2', '(특수목적고)과학고 진학자.2', '(특수목적고)외고ㆍ국제고 진학자.2']

In [123]:
raw_df2 = raw_df[use_cols]

In [124]:
# 컬럼명 사용하기 좋게 바꾸기 => 짧은 영어 변수명 스타일로 바꾸자

raw_df2.columns = ['reg', 'code', 'name', 'grad_N', 'sci_N', 'fl_N']

In [125]:
raw_df2

               reg          code              name grad_N sci_N fl_N
0               지역  정보공시 \n 학교코드               학교명     합계    합계   합계
1        서울특별시 성북구    S000003514    서울대학교사범대학부설중학교    234     4    5
2        서울특별시 종로구    S000003562  서울대학교사범대학부설여자중학교    172     0    8
3        서울특별시 강남구    S010000698             개원중학교    214     2    9
4        서울특별시 서초구    S010000700             경원중학교    310     5    4
...            ...           ...               ...    ...   ...  ...
3454   제주특별자치도 제주시    S170000844             탐라중학교    298     1    1
3455   제주특별자치도 제주시    S170000512            제주영지학교     12     0    0
3456   제주특별자치도 제주시    S170000513            제주영송학교     21     0    0
3457  제주특별자치도 서귀포시    S170000790           서귀포온성학교      9     0    0
3458   제주특별자치도 제주시    S170000870  제주제일중학교부설방송통신중학교    NaN   NaN  NaN

[3459 rows x 6 columns]

In [139]:
# 컬럼의 찌꺼기 제거
# 행 삭제 => drop
raw_df2.drop( 0 )

               reg        code              name grad_N sci_N fl_N
1        서울특별시 성북구  S000003514    서울대학교사범대학부설중학교    234     4    5
2        서울특별시 종로구  S000003562  서울대학교사범대학부설여자중학교    172     0    8
3        서울특별시 강남구  S010000698             개원중학교    214     2    9
4        서울특별시 서초구  S010000700             경원중학교    310     5    4
5        서울특별시 강남구  S010000701             구룡중학교    256     3    4
...            ...         ...               ...    ...   ...  ...
3454   제주특별자치도 제주시  S170000844             탐라중학교    298     1    1
3455   제주특별자치도 제주시  S170000512            제주영지학교     12     0    0
3456   제주특별자치도 제주시  S170000513            제주영송학교     21     0    0
3457  제주특별자치도 서귀포시  S170000790           서귀포온성학교      9     0    0
3458   제주특별자치도 제주시  S170000870  제주제일중학교부설방송통신중학교    NaN   NaN  NaN

[3458 rows x 6 columns]

In [141]:
raw_df3

               reg        code              name grad_N sci_N fl_N
1        서울특별시 성북구  S000003514    서울대학교사범대학부설중학교    234     4    5
2        서울특별시 종로구  S000003562  서울대학교사범대학부설여자중학교    172     0    8
3        서울특별시 강남구  S010000698             개원중학교    214     2    9
4        서울특별시 서초구  S010000700             경원중학교    310     5    4
5        서울특별시 강남구  S010000701             구룡중학교    256     3    4
...            ...         ...               ...    ...   ...  ...
3454   제주특별자치도 제주시  S170000844             탐라중학교    298     1    1
3455   제주특별자치도 제주시  S170000512            제주영지학교     12     0    0
3456   제주특별자치도 제주시  S170000513            제주영송학교     21     0    0
3457  제주특별자치도 서귀포시  S170000790           서귀포온성학교      9     0    0
3458   제주특별자치도 제주시  S170000870  제주제일중학교부설방송통신중학교    NaN   NaN  NaN

[3458 rows x 6 columns]

In [142]:
# 결측 데이터 처리
# NaN
# 1. 있어야 할게 없음(예외사항)
# 2. 논리적으로 발생이 안되는 경우

In [145]:
# raw_df3 == Nan (X)
raw_df3.isna().sum() # 파이썬에서 True = 1인걸 이용해서 NaN(결측데이터) 개수 확인

reg        2
code       0
name       0
grad_N    34
sci_N     34
fl_N      34
dtype: int64

In [147]:
# 어떤 데이터가 타깃인지?
raw_df3[ raw_df3['reg'].isna()]
# case1)

      reg        code   name grad_N sci_N fl_N
588   NaN  S020002009  신정중학교    317     1    5
3011  NaN  S150002889  은풍중학교     15     0    0

In [149]:
# loc 사용해서 값 수정하기
raw_df3.loc[588,'reg'] = '서울특별시 마포구'
raw_df3.loc[3011,'reg'] = '부산광역시 해운대구'

In [151]:
raw_df4 = raw_df3.dropna()

In [157]:
raw_df4.isna().sum()

reg       0
code      0
name      0
grad_N    0
sci_N     0
fl_N      0
dtype: int64

In [153]:
# 데이터 타입체크
raw_df4

               reg        code              name grad_N sci_N fl_N
1        서울특별시 성북구  S000003514    서울대학교사범대학부설중학교    234     4    5
2        서울특별시 종로구  S000003562  서울대학교사범대학부설여자중학교    172     0    8
3        서울특별시 강남구  S010000698             개원중학교    214     2    9
4        서울특별시 서초구  S010000700             경원중학교    310     5    4
5        서울특별시 강남구  S010000701             구룡중학교    256     3    4
...            ...         ...               ...    ...   ...  ...
3453   제주특별자치도 제주시  S170000838             오름중학교    193     0    5
3454   제주특별자치도 제주시  S170000844             탐라중학교    298     1    1
3455   제주특별자치도 제주시  S170000512            제주영지학교     12     0    0
3456   제주특별자치도 제주시  S170000513            제주영송학교     21     0    0
3457  제주특별자치도 서귀포시  S170000790           서귀포온성학교      9     0    0

[3424 rows x 6 columns]

In [155]:
raw_df4.dtypes

reg       str
code      str
name      str
grad_N    str
sci_N     str
fl_N      str
dtype: object

In [ ]:
int( raw_df4.loc[1, 'grad_N'] )

In [158]:
# pd.to_numeric( raw_df4['grad_N'])
# 바뀐 결과가 만들어짐
raw_df4['grad_N'] = pd.to_numeric( raw_df4['grad_N'])
raw_df4['sci_N'] = pd.to_numeric( raw_df4['sci_N'])

In [159]:
raw_df4

               reg        code              name  grad_N  sci_N fl_N
1        서울특별시 성북구  S000003514    서울대학교사범대학부설중학교     234      4    5
2        서울특별시 종로구  S000003562  서울대학교사범대학부설여자중학교     172      0    8
3        서울특별시 강남구  S010000698             개원중학교     214      2    9
4        서울특별시 서초구  S010000700             경원중학교     310      5    4
5        서울특별시 강남구  S010000701             구룡중학교     256      3    4
...            ...         ...               ...     ...    ...  ...
3453   제주특별자치도 제주시  S170000838             오름중학교     193      0    5
3454   제주특별자치도 제주시  S170000844             탐라중학교     298      1    1
3455   제주특별자치도 제주시  S170000512            제주영지학교      12      0    0
3456   제주특별자치도 제주시  S170000513            제주영송학교      21      0    0
3457  제주특별자치도 서귀포시  S170000790           서귀포온성학교       9      0    0

[3424 rows x 6 columns]

In [161]:
grad_df = raw_df4.reset_index(drop = True)

In [162]:
raw_df4

               reg        code              name  grad_N  sci_N fl_N
1        서울특별시 성북구  S000003514    서울대학교사범대학부설중학교     234      4    5
2        서울특별시 종로구  S000003562  서울대학교사범대학부설여자중학교     172      0    8
3        서울특별시 강남구  S010000698             개원중학교     214      2    9
4        서울특별시 서초구  S010000700             경원중학교     310      5    4
5        서울특별시 강남구  S010000701             구룡중학교     256      3    4
...            ...         ...               ...     ...    ...  ...
3453   제주특별자치도 제주시  S170000838             오름중학교     193      0    5
3454   제주특별자치도 제주시  S170000844             탐라중학교     298      1    1
3455   제주특별자치도 제주시  S170000512            제주영지학교      12      0    0
3456   제주특별자치도 제주시  S170000513            제주영송학교      21      0    0
3457  제주특별자치도 서귀포시  S170000790           서귀포온성학교       9      0    0

[3424 rows x 6 columns]

In [ ]:
# Pandas의 주요기능 5가지
- 시리즈의 연산
- 정렬과 필터링
- apply
- groupby & pivot
- merge

In [170]:
# 시리즈의 연산
# 각 중학교의 특목고 진학 숫자
grad_df['spc_N'] = grad_df['sci_N'] + grad_df['fl_N']

In [172]:
# 특목고 진학률
grad_df['spc_R'] = grad_df['spc_N'] / grad_df['grad_N'] * 100

In [174]:
(grad_df['spc_N'] / grad_df['grad_N'] * 100).round(2)

0       3.85
1       4.65
2       5.14
3       2.90
4       2.73
        ...
3419    2.59
3420    0.67
3421    0.00
3422    0.00
3423    0.00
Length: 3424, dtype: float64

In [169]:
grad_df['fl_N'] = pd.to_numeric(grad_df['fl_N'], errors='coerce')

grad_df['spc_N'] = grad_df['sci_N'] + grad_df['fl_N']

In [168]:
grad_df.dtypes

reg         str
code        str
name        str
grad_N    int64
sci_N     int64
fl_N        str
dtype: object

In [173]:
grad_df

,reg,code,name,grad_N,sci_N,fl_N,spc_N,spc_R
0,서울특별시 성북구,S000003514,서울대학교사범대학부설중학교,234,4,5,9,3.846154
1,서울특별시 종로구,S000003562,서울대학교사범대학부설여자중학교,172,0,8,8,4.651163
2,서울특별시 강남구,S010000698,개원중학교,214,2,9,11,5.140187
3,서울특별시 서초구,S010000700,경원중학교,310,5,4,9,2.903226
4,서울특별시 강남구,S010000701,구룡중학교,256,3,4,7,2.734375
...,...,...,...,...,...,...,...,...
3419,제주특별자치도 제주시,S170000838,오름중학교,193,0,5,5,2.590674
3420,제주특별자치도 제주시,S170000844,탐라중학교,298,1,1,2,0.671141
3421,제주특별자치도 제주시,S170000512,제주영지학교,12,0,0,0,0.000000
3422,제주특별자치도 제주시,S170000513,제주영송학교,21,0,0,0,0.000000
3423,제주특별자치도 서귀포시,S170000790,서귀포온성학교,9,0,0,0,0.000000

In [179]:
# 정렬과 필터링
# 특목고 진학률 높은 학교 top20

In [178]:
grad_df.sort_values('spc_R', ascending=False)[:20]
# .head(20)

,reg,code,name,grad_N,sci_N,fl_N,spc_N,spc_R
1820,경기도 고양시 덕양구,S090005829,티엘비유글로벌학교(중),10,0,7,7,70.000000
1665,경기도 가평군,S090005419,청심국제중학교,100,0,48,48,48.000000
474,부산광역시 부산진구,S020000969,부산국제중학교,23,6,5,11,47.826087
2362,전라북도 군산시,S130000563,선유도중학교,3,0,1,1,33.333333
292,서울특별시 광진구,S010002151,대원국제중학교,164,5,32,37,22.560976
2233,충청남도 청양군,S120000822,동영중학교,5,0,1,1,20.000000
319,서울특별시 강북구,S010002279,영훈국제중학교,158,7,23,30,18.987342
2592,전라남도 구례군,S140000636,구례북중학교,11,1,1,2,18.181818
2010,충청북도 괴산군,S110000274,청천중학교,12,0,2,2,16.666667
2345,전라북도 고창군,S130000475,심원중학교,6,1,0,1,16.666667
749,인천광역시 옹진군,S040000417,대청중학교,7,0,1,1,14.285714
1870,강원도 양구군,S100001090,대암중학교,7,1,0,1,14.285714
449,부산광역시 금정구,S020000780,브니엘예술중학교,58,0,8,8,13.793103
3154,경상남도 남해군,S160001258,물건중학교,8,1,0,1,12.500000
3380,제주특별자치도 제주시,S170000163,신창중학교,16,0,2,2,12.500000
590,부산광역시 강서구,S020002219,명지중학교,64,0,8,8,12.500000
1092,울산광역시 북구,S070000331,강동중학교,34,1,3,4,11.764706
2064,충청북도 청주시 상당구,S110000800,문의중학교,17,0,2,2,11.764706
1378,경기도 안산시 상록구,S090002694,성안중학교,309,32,4,36,11.650485
3347,경상남도 창원시 성산구,S160003406,삼정자중학교,251,14,15,29,11.553785

In [183]:
# 졸업생 숫자가 100명 이상인 학교 중에서 특목고 진학률 높은 학교 top 20
temp = grad_df[grad_df['grad_N'] >= 100]
temp.sort_values('spc_R', ascending = False)[:20]

# cond1 = grad_df['grad_N'] >= 100
# grad_df[cond1].head(20)

               reg        code     name  grad_N  sci_N  fl_N  spc_N      spc_R
1665       경기도 가평군  S090005419  청심국제중학교     100      0    48     48  48.000000
292      서울특별시 광진구  S010002151  대원국제중학교     164      5    32     37  22.560976
319      서울특별시 강북구  S010002279  영훈국제중학교     158      7    23     30  18.987342
1378   경기도 안산시 상록구  S090002694    성안중학교     309     32     4     36  11.650485
3347  경상남도 창원시 성산구  S160003406   삼정자중학교     251     14    15     29  11.553785
583       부산광역시 남구  S020002007   오륙도중학교     151      3    13     16  10.596026
577     부산광역시 해운대구  S020001893    해강중학교     350      7    29     36  10.285714
11       서울특별시 강남구  S010000709    도곡중학교     229     11    12     23  10.043668
1013     대전광역시 유성구  S060000450    대덕중학교     193      7    12     19   9.844560
1408       경기도 과천시  S090003014  과천문원중학교     387      3    35     38   9.819121
1428   경기도 안양시 동안구  S090003039    평촌중학교     441      8    34     42   9.523810
1179  경기도 고양시 일산서구  S090000958    신일중학교     364     10    24     34   9.340659
237      서울특별시 도봉구  S010001726    창동중학교     248      1    21     22   8.870968
824      인천광역시 부평구  S040000785   산곡남중학교     306     10    17     27   8.823529
579     부산광역시 해운대구  S020001910    센텀중학교     320      5    23     28   8.750000
812      인천광역시 부평구  S040000773    부원중학교     309     10    17     27   8.737864
552      부산광역시 수영구  S020001624    동아중학교     162      0    14     14   8.641975
453      부산광역시 동래구  S020000789    여명중학교     259     14     8     22   8.494208
848      인천광역시 부평구  S040001806    진산중학교     304     10    15     25   8.223684
24       서울특별시 서초구  S010000722    신동중학교     256     14     7     21   8.203125

In [187]:
# 과고 진학자 숫자가 1명 이상이고, 외고 진학자 숫자도 1명 이상인 학교중
# 특목고 진학률 높은 학교 top20
temp = grad_df[
    (grad_df['sci_N']>=1) & 
    (grad_df['fl_N']>=1)
]

temp.sort_values('spc_R', ascending = False)[:20]

,reg,code,name,grad_N,sci_N,fl_N,spc_N,spc_R
474,부산광역시 부산진구,S020000969,부산국제중학교,23,6,5,11,47.826087
292,서울특별시 광진구,S010002151,대원국제중학교,164,5,32,37,22.560976
319,서울특별시 강북구,S010002279,영훈국제중학교,158,7,23,30,18.987342
2592,전라남도 구례군,S140000636,구례북중학교,11,1,1,2,18.181818
1092,울산광역시 북구,S070000331,강동중학교,34,1,3,4,11.764706
1378,경기도 안산시 상록구,S090002694,성안중학교,309,32,4,36,11.650485
3347,경상남도 창원시 성산구,S160003406,삼정자중학교,251,14,15,29,11.553785
1153,세종특별자치시 세종특별자치시,S080000152,어진중학교,46,1,4,5,10.869565
583,부산광역시 남구,S020002007,오륙도중학교,151,3,13,16,10.596026
577,부산광역시 해운대구,S020001893,해강중학교,350,7,29,36,10.285714
11,서울특별시 강남구,S010000709,도곡중학교,229,11,12,23,10.043668
1013,대전광역시 유성구,S060000450,대덕중학교,193,7,12,19,9.844560
1408,경기도 과천시,S090003014,과천문원중학교,387,3,35,38,9.819121
537,부산광역시 서구,S020001429,송도중학교,93,4,5,9,9.677419
1872,강원도 양구군,S100001093,양구여자중학교,73,1,6,7,9.589041
1428,경기도 안양시 동안구,S090003039,평촌중학교,441,8,34,42,9.523810
1179,경기도 고양시 일산서구,S090000958,신일중학교,364,10,24,34,9.340659
237,서울특별시 도봉구,S010001726,창동중학교,248,1,21,22,8.870968
824,인천광역시 부평구,S040000785,산곡남중학교,306,10,17,27,8.823529
579,부산광역시 해운대구,S020001910,센텀중학교,320,5,23,28,8.750000

In [188]:
# 필터링 정렬 연습

import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

In [195]:
tip_df = sns.load_dataset('tips')

In [193]:
# 1. 팁 비율을 구해서 퍼센티지로 계산하고 'tip_ratio' 라는 컬럼을 만드세요
# 2. 남자고 담배 피는 사람 중 tip_ratio top 20을 구하세요

In [199]:
tip_df['tip_ratio'] = (tip_df['tip'] / tip_df['total_bill'] * 100).round(2)

In [200]:
tip_df

     total_bill   tip     sex smoker   day    time  size  tip_ratio
0         16.99  1.01  Female     No   Sun  Dinner     2       5.94
1         10.34  1.66    Male     No   Sun  Dinner     3      16.05
2         21.01  3.50    Male     No   Sun  Dinner     3      16.66
3         23.68  3.31    Male     No   Sun  Dinner     2      13.98
4         24.59  3.61  Female     No   Sun  Dinner     4      14.68
..          ...   ...     ...    ...   ...     ...   ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3      20.39
240       27.18  2.00  Female    Yes   Sat  Dinner     2       7.36
241       22.67  2.00    Male    Yes   Sat  Dinner     2       8.82
242       17.82  1.75    Male     No   Sat  Dinner     2       9.82
243       18.78  3.00  Female     No  Thur  Dinner     2      15.97

[244 rows x 8 columns]

In [211]:
tip_df[(tip_df['sex'] == 'Male') & (tip_df['smoker'] == 'Yes')].sort_values('tip_ratio', ascending = False)[:20]

     total_bill    tip   sex smoker   day    time  size  tip_ratio
172        7.25   5.15  Male    Yes   Sun  Dinner     2      71.03
183       23.17   6.50  Male    Yes   Sun  Dinner     4      28.05
181       23.33   5.65  Male    Yes   Sun  Dinner     2      24.22
194       16.58   4.00  Male    Yes  Thur   Lunch     2      24.13
174       16.82   4.00  Male    Yes   Sun  Dinner     2      23.78
222        8.58   1.92  Male    Yes   Fri   Lunch     1      22.38
200       18.71   4.00  Male    Yes  Thur   Lunch     3      21.38
63        18.29   3.76  Male    Yes   Sat  Dinner     4      20.56
171       15.81   3.16  Male    Yes   Sat  Dinner     2      19.99
211       25.89   5.16  Male    Yes   Sat  Dinner     4      19.93
106       20.49   4.06  Male    Yes   Sat  Dinner     2      19.81
170       50.81  10.00  Male    Yes   Sat  Dinner     3      19.68
204       20.53   4.00  Male    Yes  Thur   Lunch     4      19.48
196       10.34   2.00  Male    Yes  Thur   Lunch     2      19.34
234       15.53   3.00  Male    Yes   Sat  Dinner     2      19.32
231       15.69   3.00  Male    Yes   Sat  Dinner     3      19.12
218        7.74   1.44  Male    Yes   Sat  Dinner     2      18.60
220       12.16   2.20  Male    Yes   Fri   Lunch     2      18.09
62        11.02   1.98  Male    Yes   Sat  Dinner     2      17.97
189       23.10   4.00  Male    Yes   Sun  Dinner     3      17.32

In [212]:
# apply
grad_df

,reg,code,name,grad_N,sci_N,fl_N,spc_N,spc_R
0,서울특별시 성북구,S000003514,서울대학교사범대학부설중학교,234,4,5,9,3.846154
1,서울특별시 종로구,S000003562,서울대학교사범대학부설여자중학교,172,0,8,8,4.651163
2,서울특별시 강남구,S010000698,개원중학교,214,2,9,11,5.140187
3,서울특별시 서초구,S010000700,경원중학교,310,5,4,9,2.903226
4,서울특별시 강남구,S010000701,구룡중학교,256,3,4,7,2.734375
...,...,...,...,...,...,...,...,...
3419,제주특별자치도 제주시,S170000838,오름중학교,193,0,5,5,2.590674
3420,제주특별자치도 제주시,S170000844,탐라중학교,298,1,1,2,0.671141
3421,제주특별자치도 제주시,S170000512,제주영지학교,12,0,0,0,0.000000
3422,제주특별자치도 제주시,S170000513,제주영송학교,21,0,0,0,0.000000
3423,제주특별자치도 서귀포시,S170000790,서귀포온성학교,9,0,0,0,0.000000

In [214]:
# apply
# 한 열의 모든 데이터에게 똑같은 코드를 적용해 줌
'서울특별시 성북구'.split(' ')[0]

'서울특별시'

In [216]:
def get_sido(x):
    return x.split(' ')[0]
    
grad_df['sido'] = grad_df['reg'].apply(get_sido) # for문 돌리는 대신에 apply 써서 더 간결하게

In [219]:
grad_df['sido'].unique()
# 추리고 집계한 값들

<ArrowStringArray>
[  '서울특별시',   '부산광역시',   '대구광역시',   '인천광역시',   '광주광역시',   '대전광역시',   '울산광역시',
 '세종특별자치시',     '경기도',     '강원도',    '충청북도',    '충청남도',    '전라북도',    '전라남도',
    '경상북도',    '경상남도', '제주특별자치도']
Length: 17, dtype: str

In [220]:
def get_sido(x):
    x2 = x.split(' ')[0]
    if len(x2) == 4:
        return x2[0] + x2[3]
    else :
        return x2[:2]
grad_df['sido'] = grad_df['reg'].apply(get_sido)

In [221]:
grad_df

,reg,code,name,grad_N,sci_N,fl_N,spc_N,spc_R,sido
0,서울특별시 성북구,S000003514,서울대학교사범대학부설중학교,234,4,5,9,3.846154,서울
1,서울특별시 종로구,S000003562,서울대학교사범대학부설여자중학교,172,0,8,8,4.651163,서울
2,서울특별시 강남구,S010000698,개원중학교,214,2,9,11,5.140187,서울
3,서울특별시 서초구,S010000700,경원중학교,310,5,4,9,2.903226,서울
4,서울특별시 강남구,S010000701,구룡중학교,256,3,4,7,2.734375,서울
...,...,...,...,...,...,...,...,...,...
3419,제주특별자치도 제주시,S170000838,오름중학교,193,0,5,5,2.590674,제주
3420,제주특별자치도 제주시,S170000844,탐라중학교,298,1,1,2,0.671141,제주
3421,제주특별자치도 제주시,S170000512,제주영지학교,12,0,0,0,0.000000,제주
3422,제주특별자치도 제주시,S170000513,제주영송학교,21,0,0,0,0.000000,제주
3423,제주특별자치도 서귀포시,S170000790,서귀포온성학교,9,0,0,0,0.000000,제주

In [222]:
grad_df['spc_R'].round(0)

0       4.0
1       5.0
2       5.0
3       3.0
4       3.0
       ...
3419    3.0
3420    1.0
3421    0.0
3422    0.0
3423    0.0
Name: spc_R, Length: 3424, dtype: float64

In [233]:
# grad_df['spc_R'].round(0).apply(int)

In [236]:
grad_ff = grad_df.to_excel(r'C:\Users\KDA\Desktop\grad_df.xlsx', index = False)

In [237]:
grad_ff